Repository IAmTamal/ShopCoders, pull requests merged in 2022-09, with the labels that each got.

#52 Fixed major bugs
  context/ShopState.jsx
  pages/api/products/addproductstocart.js
  pages/user/sellproducts/[slug].jsx
Labels: bug, ⭐ goal: addition, 💻 aspect: code, 🕹 aspect: interface, 🟧 priority: high, 🛠 goal: fix, 🛠 status : Under development

#53 Fixed UI for sell products
  components/Homecontainer.jsx
  components/SellProductsForm.jsx
  pages/index.js
  pages/user/sellproducts/[slug].jsx
  styles/Footer.module.css
  styles/Home.module.css
  styles/Sellproducts.module.css
Labels: enhancement, feature, ✨ goal: improvement, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, 🛠 goal: fix, 🛠 status : Under development

#54 Products page new api
  pages/api/products/addproducts.js
  pages/user/sellproducts/[slug].jsx
Labels: feature

#57 Update feature_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: feature, ✨ goal: improvement, ✅ status : Ready for merge, 🟧 priority: high, 🤖 aspect: dx
